version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=blondimy
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"